# Generated by Django 5.2.7 on 2025-11-20 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_notification_options_alter_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='availability_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.availabilityrequest'),
        ),
        migrations.CreateModel(
            name='RequestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('availability_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.availabilityrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Request History',
                'verbose_name_plural': 'Request Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
