# Generated by Django 5.2.7 on 2025-11-21 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_notification_availability_request_requesthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('landlord', 'Landlord'), ('administrator', 'Administrator')], default='customer', max_length=20),
        ),
    ]
